[wokwi]
version = 1
firmware = '.pio\build\esp32doit-devkit-v1\firmware.bin'
elf = 'C:\Users\WINDOWS 11\OneDrive\Documents\KULIAH\SEMESTER 4\TUGAS SEMESTER 4\IoT\minggu5\wokwi_internet\.pio\build\esp32doit-devkit-v1\firmware.elf'
